### ISSUE TITLE
Cannot redefine property: createGraph

### ISSUE THREAD

**Issue by xgfd** [zazukoians/rdf-ext#11]
I believe you're aware of this; the `createGraph` property of rdf-interface is not writable and leads to an error when you try to redefine it to `createGraphExt`. This can be confusing for some users. Maybe you can include a modified version in your repository.

**Comment by bergos** [comment]
There is already a patched version on github [1] and I also packaged it for npm [2]. This should also solve the predicate/property problem.

[1] https://github.com/bergos/rdf-interfaces
[2] https://npmjs.org/package/rdf-interfaces

**Comment by xgfd** [comment]
Maybe I missed something but I did use the files from the github you gave; the createGraph property still has {writable:false}.

**Comment by bergos** [comment]
Did you use the minified version? I just noticed that the minified version was not updated. I removed that file from the repository to avoid any confusions in the future.

**Comment by xgfd** [comment]
I checked both. It still appeared to me the createGraph is not writable in rdfi.js, line 382.

**Comment by bergos** [comment]
I think the configurable property must be true, which I patched with this [1] commit, because I'm using Object.defineProperty to replace the method. Which JS environment do you work with? For me it works with node.js (0.10.*), Firefox and Chrome.

[1] https://github.com/bergos/rdf-interfaces/commit/5d76e001a16a92c13b60763fe28f597849c674ce#diff-07dd0e97cb12de929bb5c132a2385628L382
[2] https://github.com/zazukoians/rdf-ext/blob/master/rdf-ext.js#L166

**Comment by xgfd** [comment]
Ahh I mixed up your version with this one
<https://github.com/webr3/rdf-interfaces>. It's all good now. Would it make
sense to give a link in rdf-ext to your rdf-interfaces?

--
Xin Wang
University of Southampton
Electronics and Computer Science
Home page: *http://www.ecs.soton.ac.uk/people/xw4g08
<http://www.ecs.soton.ac.uk/people/xw4g08>*
Mail: xwang@soton.ac.uk

**Comment by bergos** [comment]
Thanks for you feedback. I added a list of known working implementations to the README.
